### ISSUE TITLE
Add new Group Error

### ISSUE THREAD

**Issue by JimBob0121** [Cyberbyte-Studios/CyberWorks-3#28]
* **I'm submitting a ...**
  - [X] bug report

Please only submit the section relevant to what you are submitting.

Feature Request
------

* **What would you like to see added / changed?**
point system :) for reporting players

* **What is the motivation / use case for changing / adding the behavior?**

Support Request
------

* **Details of your issue?**
Error when trying to save a new group

* **Please tell us about your environment:**

* **Checklist**
```
[Wed Feb 14 11:24:57.146128 2018] [php7:notice] [pid 2340:tid 1652] [client 81.107.157.106:61613] Slim Application Error:\r\nType: Illuminate\\Database\\QueryException\r\nCode: 23000\r\nMessage: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'group_id' cannot be null (SQL: insert into `cw_permissions` (`group_name`, `group_id`) values (test, ))\r\nFile: C:\\xampp\\htdocs\\CyberWorks\\vendor\\illuminate\\database\\Connection.php\r\nLine: 664\r\nTrace: #0 C:\\xampp\\htdocs\\CyberWorks\\vendor\\illuminate\\database\\Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into `cw...', Array, Object(Closure))\n#1 C:\\xampp\\htdocs\\CyberWorks\\vendor\\illuminate\\database\\Connection.php(459): Illuminate\\Database\\Connection->run('insert into `cw...', Array, Object(Closure))\n#2 C:\\xampp\\htdocs\\CyberWorks\\vendor\\illuminate\\database\\Connection.php(411): Illuminate\\Database\\Connection->statement('insert into `cw...', Array)\n#3 C:\\xampp\\htdocs\\CyberWorks\\vendor\\illuminate\\database\\Query\\Processors\\Processor.php(32): Illuminate\\Database\\Connection->insert('insert into `cw...', Array)\n#4 C:\\xampp\\htdocs\\CyberWorks\\vendor\\illuminate\\database\\Query\\Builder.php(2188): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId(Object(Illuminate\\Database\\Query\\Builder), 'insert into `cw...', Array, 'id')\n#5 C:\\xampp\\htdocs\\CyberWorks\\vendor\\illuminate\\database\\Eloquent\\Builder.php(1281): Illuminate\\Database\\Query\\Builder->insertGetId(Array, 'id')\n#6 C:\\xampp\\htdocs\\CyberWorks\\vendor\\illuminate\\database\\Eloquent\\Model.php(725): Illuminate\\Database\\Eloquent\\Builder->__call('insertGetId', Array)\n#7 C:\\xampp\\htdocs\\CyberWorks\\vendor\\illuminate\\database\\Eloquent\\Model.php(690): Illuminate\\Database\\Eloquent\\Model->insertAndSetId(Object(Illuminate\\Database\\Eloquent\\Builder), Array)\n#8 C:\\xampp\\htdocs\\CyberWorks\\vendor\\illuminate\\database\\Eloquent\\Model.php(553): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(Illuminate\\Database\\Eloquent\\Builder))\n#9 C:\\xampp\\htdocs\\CyberWorks\\app\\Core\\Controllers\\Auth\\GroupController.php(227): Illuminate\\Database\\Eloquent\\Model->save()\n#10 [internal function]: CyberWorks\\Core\\Controllers\\Auth\\GroupController->newGroup(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)\n#11 C:\\xampp\\htdocs\\CyberWorks\\vendor\\slim\\slim\\Slim\\Handlers\\Strategies\\RequestResponse.php(41): call_user_func(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)\n#12 C:\\xampp\\htdocs\\CyberWorks\\vendor\\slim\\slim\\Slim\\Route.php(335): Slim\\Handlers\\Strategies\\RequestResponse->__invoke(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)\n#13 C:\\xampp\\htdocs\\CyberWorks\\app\\Core\\Middleware\\Permissions\\HasPermissionMiddleware.php(23): Slim\\Route->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#14 [internal function]: CyberWorks\\Core\\Middleware\\Permissions\\HasPermissionMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))\n#15 C:\\xampp\\htdocs\\CyberWorks\\vendor\\slim\\slim\\Slim\\DeferredCallable.php(43): call_user_func_array(Object(CyberWorks\\Core\\Middleware\\Permissions\\HasPermissionMiddleware), Array)\n#16 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))\n#17 C:\\xampp\\htdocs\\CyberWorks\\vendor\\slim\\slim\\Slim\\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))\n#18 C:\\xampp\\htdocs\\CyberWorks\\app\\Core\\Middleware\\AuthenticatedMiddleware.php(21): Slim\\Route->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#19 [internal function]: CyberWorks\\Core\\Middleware\\AuthenticatedMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#20 C:\\xampp\\htdocs\\CyberWorks\\vendor\\slim\\slim\\Slim\\DeferredCallable.php(43): call_user_func_array(Object(CyberWorks\\Core\\Middleware\\AuthenticatedMiddleware), Array)\n#21 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#22 C:\\xampp\\htdocs\\CyberWorks\\vendor\\slim\\slim\\Slim\\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#23 C:\\xampp\\htdocs\\CyberWorks\\vendor\\slim\\slim\\Slim\\MiddlewareAwareTrait.php(117): Slim\\Route->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#24 C:\\xampp\\htdocs\\CyberWorks\\vendor\\slim\\slim\\Slim\\Route.php(313): Slim\\Route->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#25 C:\\xampp\\htdocs\\CyberWorks\\vendor\\slim\\slim\\Slim\\App.php(495): Slim\\Route->run(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#26 C:\\xampp\\htdocs\\CyberWorks\\app\\Core\\Middleware\\ValidationErrorsMiddleware.php(20): Slim\\App->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#27 [internal function]: CyberWorks\\Core\\Middleware\\ValidationErrorsMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))\n#28 C:\\xampp\\htdocs\\CyberWorks\\vendor\\slim\\slim\\Slim\\DeferredCallable.php(43): call_user_func_array(Object(CyberWorks\\Core\\Middleware\\ValidationErrorsMiddleware), Array)\n#29 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))\n#30 C:\\xampp\\htdocs\\CyberWorks\\vendor\\slim\\slim\\Slim\\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))\n#31 C:\\xampp\\htdocs\\CyberWorks\\app\\Core\\Middleware\\OldInputMiddleware.php(21): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#32 [internal function]: CyberWorks\\Core\\Middleware\\OldInputMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#33 C:\\xampp\\htdocs\\CyberWorks\\vendor\\slim\\slim\\Slim\\DeferredCallable.php(43): call_user_func_array(Object(CyberWorks\\Core\\Middleware\\OldInputMiddleware), Array)\n#34 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#35 C:\\xampp\\htdocs\\CyberWorks\\vendor\\slim\\slim\\Slim\\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#36 C:\\xampp\\htdocs\\CyberWorks\\app\\Core\\Middleware\\csrf\\CSRFViewMiddleware.php(29): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#37 [internal function]: CyberWorks\\Core\\Middleware\\csrf\\CSRFViewMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#38 C:\\xampp\\htdocs\\CyberWorks\\vendor\\slim\\slim\\Slim\\DeferredCallable.php(43): call_user_func_array(Object(CyberWorks\\Core\\Middleware\\csrf\\CSRFViewMiddleware), Array)\n#39 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#40 C:\\xampp\\htdocs\\CyberWorks\\vendor\\slim\\slim\\Slim\\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#41 C:\\xampp\\htdocs\\CyberWorks\\app\\Core\\Middleware\\csrf\\CSRFHeaderMiddleware.php(37): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#42 [internal function]: CyberWorks\\Core\\Middleware\\csrf\\CSRFHeaderMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))\n#43 C:\\xampp\\htdocs\\CyberWorks\\vendor\\slim\\slim\\Slim\\DeferredCallable.php(43): call_user_func_array(Object(CyberWork
```

https://hastebin.com/ofohevojib.tex
* **Other information**

**Comment by MightySCollins** [comment]
Should have said this was fixed in #23. We will release shortly
