### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by RustyRekts** [Cyberbyte-Studios/CyberWorks-3#95]
* **I'm submitting a ...**
  - [ ] support request

Support Request
------

* **Details of your issue?**
Displaying Error - Slim Application Error

* **Please tell us about your environment:**
Arma 3 roleplay server

* **CyberWorks 3 Version:**
1.1.4 - Latest

* **Checklist**
  - [ ] Attached Relevant Logs
  - [ ] Screenshots

* **Other information**

Logs:

[Fri Jul 03 19:22:35.866670 2020] [proxy_fcgi:error] [pid 5328] [client 82.16.3.195:53175] AH01071: Got error 'Primary script unknown'
[7:20 PM]
primary script unknown(edited)
[7:21 PM]
Got error 'PHP message: Slim Application Error:\nType: Error\nMessage: Class 'Twig_Extension' not found\nFile: /var/www/vhosts/reduxroleplay.com/cpredux/app/Extension/TranslationExtension.php\nLine: 7\nTrace: #0 /var/www/vhosts/reduxroleplay.com/cpredux/vendor/composer/ClassLoader.php(444): include()\n#1 /var/www/vhosts/reduxroleplay.com/cpredux/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()\n#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()\n#3 /var/www/vhosts/reduxroleplay.com/cpredux/bootstrap/app.php(81): spl_autoload_call()\n#4 /var/www/vhosts/reduxroleplay.com/cpredux/vendor/pimple/pimple/src/Pimple/Container.php(118): {closure}()\n#5 /var/www/vhosts/reduxroleplay.com/cpredux/vendor/slim/slim/Slim/Container.php(109): Pimple\Container->offsetGet()\n#6 /var/www/vhosts/reduxroleplay.com/cpredux/vendor/slim/slim/Slim/Container.php(164): Slim\Container->get()\n#7 /var/www/vhosts/reduxroleplay.com/cpredux/app/Core/Middleware/csrf/CSRFViewMiddleware.php(11): Slim\Container->__get()...'

Screenshot:

![ae544b2eb099ef0683729ac9ffacbc1f](https://user-images.githubusercontent.com/35163503/86492200-3bbfe600-bd65-11ea-937f-ee82d95dd282.png)

this is when i try going to my subdomain i have setup, "https://cp.reduxroleplay.com/public". I cannot manage to find out what the issue is, could someone please help?

**Comment by UltimateByte** [comment]
Hello,
Server sysadmin here.
It should be noted that the server is running CentOS 7 with Plesk 18.0.28.

Composer dependencies were installed via Plesk, and install went OK. Other apps are using it on the server with no issues.

![image](https://user-images.githubusercontent.com/8805941/86493306-5f892900-bd71-11ea-9bf5-7c68a8856767.png)

With PHP 7.1 and 7.2, the error shortens that way:

```
2020-07-03 21:04:09 | Error | x.x.x.x |   | AH01071: Got error 'PHP message: PHP Fatal error:  Class 'Twig_Extension' not found in /var/www/vhosts/reduxroleplay.com/cpredux/app/Extension/TranslationExtension.php on line 7\n' |   |   |   | Apache error
```

Any help appreciated.
